### ISSUE TITLE
source of twitter accounts

### ISSUE THREAD

**Issue by tttp** [tamedia-ddj/parlamentarier_twitter#1]
Hi,

Could you share with me where you found the list of twitter accounts or the scraper you used?

https://github.com/tamedia-ddj/parlamentarier_twitter/blob/master/data/twitter_accounts_2019_edited.csv

Much appreciated!

**Comment by s1co** [comment]
Hi!

You can find my, pretty simple, approach here: https://github.com/tamedia-ddj/parlamentarier_twitter/blob/master/0_Twitter_Parlament.ipynb
To initially populate the list, I did some Google Search requests based on the members of parliament taken from wikipedia. Then I checked the results manually and, where necessary, edited the list by hand.

Hope this helps! Cheers!
